apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-app-memory-boomb-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  script.sh: |
    #!/bin/bash
    echo "Starting memory bomb..."
    my_array=()
    while true; do
      my_array+=("apple banana cherry absorbing your RAM")
      sleep 0.1
    done 