apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-app-memory-boomb-config
annotations:
  argocd.argoproj.io/sync-wave: "-1"
data: |
  #/bin/bash
  while true; do
    my_string="apple banana cherry"
    read -ra my_array <<< "$my_string"
    sleep 0.1
  done 