apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaleobject
  namespace: default
spec:
  scaleTargetRef:
    name: stress-app
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: container_cpu_usage_seconds_total
      threshold: '0.15' # Scale up if CPU hits 150m
      query: "sum(rate(container_cpu_usage_seconds_total{namespace='default', pod=~'stress-app.*'}[2m])) by (pod)"