apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaleobject
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  scaleTargetRef:
    name: memory-app
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: memory
    metricType: utilization
    metadata:
      value: 35Mi
      containerName: "memory-app"