---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-app
spec:
  selector:
    matchLabels:
      app: stress-app
  template:
    metadata:
      labels:
        app: stress-app
    spec:
      containers:
      - name: stress-app
        image: stress-app:1.0.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"