---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-app
  template:
    metadata:
      labels:
        app: memory-app
    spec:
      containers:
      - name: memoru-app
        image: ubuntu:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "/app/memory-boomb-script.sh"]
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "100Mi"
        volumeMounts:
        - name: memory-boomb-script
          mountPath: /app
     
      volumes:
      - name: memory-boomb-script
        configMap:
          name: stress-app-memory-boomb-config
          defaultMode: 0755